"""Adicionar modelo Invite para sistema de convites

Revision ID: 9fec16bf175b
Revises: 17cb65390b60
Create Date: 2025-10-06 08:23:38.816204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fec16bf175b'
down_revision = '17cb65390b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=120), nullable=False),
    sa.Column('service_title', sa.String(length=200), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_orders_invite_id', 'invites', ['invite_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_invite_id', type_='foreignkey')
        batch_op.drop_column('invite_id')

    op.drop_table('invites')
    # ### end Alembic commands ###
