"""Add order management fields for 36h confirmation system

Revision ID: b505d3ad62cb
Revises: 60679096b063
Create Date: 2025-11-14 10:11:20.208140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b505d3ad62cb'
down_revision = '60679096b063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('service_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dispute_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cancellation_fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('dispute_evidence', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dispute_client_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dispute_provider_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dispute_admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dispute_winner', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('platform_fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('contestation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key('fk_orders_cancelled_by', 'users', ['cancelled_by'], ['id'])

    with op.batch_alter_table('proposal_alerts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_proposal_alerts_alert_type'))
        batch_op.drop_index(batch_op.f('idx_proposal_alerts_created_at'))
        batch_op.drop_index(batch_op.f('idx_proposal_alerts_severity'))
        batch_op.drop_index(batch_op.f('idx_proposal_alerts_status'))
        batch_op.drop_index(batch_op.f('idx_proposal_alerts_status_severity'))
        batch_op.drop_index(batch_op.f('idx_proposal_alerts_user_id'))

    with op.batch_alter_table('proposal_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_proposal_audit_logs_action_type'))
        batch_op.drop_index(batch_op.f('idx_proposal_audit_logs_action_user_date'))
        batch_op.drop_index(batch_op.f('idx_proposal_audit_logs_actor_role'))
        batch_op.drop_index(batch_op.f('idx_proposal_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('idx_proposal_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('idx_proposal_audit_logs_invite_id'))
        batch_op.drop_index(batch_op.f('idx_proposal_audit_logs_proposal_id'))

    with op.batch_alter_table('proposal_metrics', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_proposal_metrics_date_type'))
        batch_op.drop_index(batch_op.f('idx_proposal_metrics_type_date'))
        batch_op.create_unique_constraint('unique_metric_date_type', ['metric_date', 'metric_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal_metrics', schema=None) as batch_op:
        batch_op.drop_constraint('unique_metric_date_type', type_='unique')
        batch_op.create_index(batch_op.f('idx_proposal_metrics_type_date'), ['metric_type', 'metric_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_metrics_date_type'), ['metric_date', 'metric_type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('proposal_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_proposal_audit_logs_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_audit_logs_invite_id'), ['invite_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_audit_logs_actor_role'), ['actor_role'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_audit_logs_action_user_date'), ['action_type', 'actor_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('proposal_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_proposal_alerts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_alerts_status_severity'), ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_proposal_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_cancelled_by', type_='foreignkey')
        batch_op.drop_column('contestation_fee')
        batch_op.drop_column('platform_fee_percentage')
        batch_op.drop_column('platform_fee')
        batch_op.drop_column('dispute_winner')
        batch_op.drop_column('dispute_admin_notes')
        batch_op.drop_column('dispute_provider_response')
        batch_op.drop_column('dispute_client_statement')
        batch_op.drop_column('dispute_evidence')
        batch_op.drop_column('cancellation_fee_percentage')
        batch_op.drop_column('cancellation_fee')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('dispute_deadline')
        batch_op.drop_column('confirmation_deadline')
        batch_op.drop_column('service_deadline')
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###
